### ISSUE TITLE
Generated pact file body include json_class, contents information and doesn't have matchingRules section

### ISSUE THREAD

**Issue by YingzheHeBetty** [pact-foundation/pact-specification#85] opened 2021-02-10 17:44 UTC
Hi,

I used ruby pact gem version 1.54 (also checked the latest version, had the same issue)
And I defined the interaction in rspec file like this:
```
    expected_response_body = {
              'totalLineItemsCount'=> 7,
              'onTargetLineItemsCount'=> 2,
              'overPacingLineItemsCount'=> 2,
              'underPacingLineItemsCount'=> 3
          }
          analytics_service
              .given("Agency user exist")
              .upon_receiving("a get request for line item pacing dashboard widget")
              .with(method: "get",
                    path: "/v1/dashboard/widgets/line_items_pacing",
                    query:
                        {currentDate: "2021-02-08"}
                    )
              .will_respond_with(status: 200,
                                 headers: {"Content-Type" => "application/json"},
                                 body:
                                     Pact.like(expected_response_body)

                                )
```
The generated pact file is below:
```

  "consumer": {
    "name": "CMM"
  },
  "provider": {
    "name": "Analytics Service"
  },
  "interactions": [
    {
      "description": "a get request for line item pacing dashboard widget",
      "providerState": "Agency user exist",
      "request": {
        "method": "get",
        "path": "/v1/dashboard/widgets/line_items_pacing",
        "query": "currentDate=2021-02-08"
      },
      "response": {
        "status": 200,
        "headers": {
          "Content-Type": "application/json"
        },
        "body": {
          "json_class": "Pact::SomethingLike",
          "contents": {
            "totalLineItemsCount": 7,
            "onTargetLineItemsCount": 2,
            "overPacingLineItemsCount": 2,
            "underPacingLineItemsCount": 3
          }
        }
      }
    }
  ],
  "metadata": {
    "pactSpecification": {
      "version": "2.0.0"
    }
  }
}
```
Noticed that in the body response, it not only returned the expected values but also returned json_class, contents etc. Because of this, on the provider side, the test failed because of the body mismatch.

**Comment by bethesque** [comment] 2021-02-11 00:15
The JSON class definitely shouldn't be in there. Can you please raise this in the https://github.com/pact-foundation/pact-ruby repository, and create a reproducible code example using this repo please https://github.com/pact-foundation/pact-ruby-e2e-example. 

I'm closing this issue just because it is in the wrong place, expecting another to be raised.

**Closed by bethesque** 2021-02-11 00:15 UTC

**Comment by YingzheHeBetty** [comment] 2021-02-17 04:33
Hi Beth,

Is there anything code base example for rails application using Pact?

Regards,
Betty

Beth Skurrie <notifications@github.com> 于2021年2月10日周三 下午7:15写道：
